author: K900 
database: false 
description: /tgm used to stand for Toggle God Mode in TES series, but now it's Toggle Game Mode.
main: me.k900.plugins.tgm.ToggleGameMode
name: TGM
startup: postworld
version: '0.1'
commands:
    tgm:
        description: Toggle gamemode
        aliases: [m, mode]
        usage: |
          /tgm - toggle game mode for yourself
          /tgm K900 - toggle game mode for K900
          /tgm c/s - switch your game mode to creative/survival
          /tgm K900 c/s - switch K900's game mode to creative/survival
    permissions:
        tgm.self:
            default: op
            description: Can change gamemode for him/herself
        tgm.others:
            default: op
            description: Can change gamemode for others
